// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLUXEKI3ui025hzmB4utgCieNrBrSpmaI',
    appId: '1:262564490278:web:2a9436a512f671edcccae7',
    messagingSenderId: '262564490278',
    projectId: 'datatricksai',
    authDomain: 'datatricksai.firebaseapp.com',
    storageBucket: 'datatricksai.firebasestorage.app',
    measurementId: 'G-ZZHH4K90N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9YFakpK-2mbJr1nhlbCARJB2k4Ld6B8w',
    appId: '1:262564490278:android:f30ad817d8a9c2eecccae7',
    messagingSenderId: '262564490278',
    projectId: 'datatricksai',
    storageBucket: 'datatricksai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX_lt377ux3PfcAT4sEb4CRhOox_SA3oQ',
    appId: '1:262564490278:ios:23486a2baa724a0bcccae7',
    messagingSenderId: '262564490278',
    projectId: 'datatricksai',
    storageBucket: 'datatricksai.firebasestorage.app',
    iosBundleId: 'com.example.datatricksai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX_lt377ux3PfcAT4sEb4CRhOox_SA3oQ',
    appId: '1:262564490278:ios:23486a2baa724a0bcccae7',
    messagingSenderId: '262564490278',
    projectId: 'datatricksai',
    storageBucket: 'datatricksai.firebasestorage.app',
    iosBundleId: 'com.example.datatricksai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLUXEKI3ui025hzmB4utgCieNrBrSpmaI',
    appId: '1:262564490278:web:47cc8b48a50ee1adcccae7',
    messagingSenderId: '262564490278',
    projectId: 'datatricksai',
    authDomain: 'datatricksai.firebaseapp.com',
    storageBucket: 'datatricksai.firebasestorage.app',
    measurementId: 'G-KEYBYDKL67',
  );
}
