import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // REQUIRED: Core Firebase package
import 'firebase_options.dart'; // REQUIRED: Generated by FlutterFire
import 'package:flutter_web_plugins/url_strategy.dart'; // REQUIRED: For clean web URLs

// PAGE IMPORTS
import 'package:datatricksai/pages/landing_page.dart';
import 'package:datatricksai/pages/auth_page.dart';
import 'package:datatricksai/pages/careers_page.dart';
import 'package:datatricksai/pages/admin_dashboard.dart';
import 'package:datatricksai/pages/user_dashboard.dart';

// ===========================================================================
// MAIN ENTRY POINT
// ===========================================================================

void main() async {
  // 1. Lock the Flutter binding before doing asynchronous work
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Enable Clean URLs (Removes the '#' from Flutter Web paths)
  usePathUrlStrategy();

  // 3. Initialize Firebase using the generated options
  // (This connects the app to your specific Firebase project keys)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 4. Run the App
  runApp(const DataTricksApp());
}

class DataTricksApp extends StatelessWidget {
  const DataTricksApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'DataTricks AI | The Human Intelligence Layer',
      debugShowCheckedModeBanner: false,

      // THEME CONFIGURATION
      theme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF020408),
        primaryColor: const Color(0xFF6366F1), // Indigo
        fontFamily: 'Inter',
        useMaterial3: true,

        colorScheme: const ColorScheme.dark(
          primary: Color(0xFF6366F1),
          secondary: Color(0xFFEC4899), // Pink
          surface: Color(0xFF0F172A),
          background: Color(0xFF020408),
        ),

        textTheme: const TextTheme(
          displayLarge: TextStyle(
            fontSize: 76,
            fontWeight: FontWeight.w900,
            letterSpacing: -3.0,
            height: 1.05,
            color: Colors.white,
          ),
          displayMedium: TextStyle(
            fontSize: 48,
            fontWeight: FontWeight.w800,
            letterSpacing: -1.0,
            color: Colors.white,
          ),
          bodyLarge: TextStyle(
            fontSize: 18,
            color: Color(0xFF94A3B8), // Slate 400
            height: 1.6,
          ),
        ),
      ),

      // STATIC ROUTES
      initialRoute: '/',
      routes: {
        '/':        (context) => const LandingPage(),
        '/auth':    (context) => const AuthPage(),
        '/careers': (context) => const CareersPage(),
        '/admin':   (context) => const AdminDashboard(),
      },

      // /dashboard uses onGenerateRoute so it can receive
      // the userEmail as a navigation argument from AuthPage:
      //
      //   Navigator.pushNamedAndRemoveUntil(
      //     context, '/dashboard', (r) => false,
      //     arguments: 'user@example.com',
      //   );
      //
      onGenerateRoute: (settings) {
        if (settings.name == '/dashboard') {
          final email = settings.arguments as String? ?? '';
          return MaterialPageRoute(
            builder: (context) => UserDashboard(userEmail: email),
          );
        }
        return null;
      },
    );
  }
}